import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { brands, brandById } from "@/data/brands";
import { films } from "@/data/films";
import { cameras } from "@/data/cameras";
import { countryFlag } from "@/data/countries";
import { FilmCard, CameraCard } from "@/components/cards";
type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return brands.map(x=>({slug:x.id}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const brand=brandById[slug];return {title:brand?.name||"브랜드를 찾을 수 없음",description:brand?.character};}
export default async function Page({params}:Props){const {slug}=await params;const brand=brandById[slug];if(!brand)notFound();const ownFilms=films.filter(x=>x.brandId===brand.id);const ownCameras=cameras.filter(x=>x.brandId===brand.id);const exclusive=ownCameras.filter(x=>x.stockStatus==="camera-exclusive");return <div className="container page-shell"><div className="detail-breadcrumb"><Link href="/brands">BRANDS</Link> / {brand.name.toUpperCase()}</div><div className="page-heading"><span className="section-kicker">{countryFlag(brand.country)} {brand.country.toUpperCase()} · {brand.group.toUpperCase()}</span><h1>{brand.name}</h1><p>{brand.character}</p></div><div className="relation-grid" style={{maxWidth:750,marginBottom:34}}><div className="relation-card"><small>브랜드 형태</small><b>{brand.form}</b></div><div className="relation-card"><small>실제 제조 여부</small><b>{brand.makesFilm?"자체 제조 제품 있음":"브랜드별·제품별 확인 필요"}</b></div>{brand.manufacturer&&<div className="relation-card"><small>실제 제조사</small><b>{brand.manufacturer}</b></div>}{brand.parentCompany&&<div className="relation-card"><small>모회사</small><b>{brand.parentCompany}</b></div>}<div className="relation-card"><small>등록 필름</small><b>{ownFilms.length}개</b></div><div className="relation-card"><small>카메라 / 전용 내장필름</small><b>{ownCameras.length}개 / {exclusive.length}개</b></div></div>{ownFilms.length>0&&<section className="section-block" style={{paddingTop:10}}><div className="section-heading"><div><span className="section-kicker">FILMOGRAPHY</span><h2>대표 필름</h2></div></div><div className="card-grid">{ownFilms.map(x=><FilmCard key={x.id} film={x}/>)}</div></section>}{ownCameras.length>0&&<section className="section-block"><div className="section-heading"><div><span className="section-kicker">CAMERA ARCHIVE</span><h2>일회용·재장전 카메라</h2></div></div><div className="card-grid">{ownCameras.map(x=><CameraCard key={x.id} camera={x}/>)}</div></section>}{!ownFilms.length&&!ownCameras.length&&<div className="empty-state"><h3>검증된 제품 정보를 준비 중입니다.</h3><p>브랜드는 등록되어 있지만, 공개 자료로 확인할 수 있는 필름·카메라 레코드는 아직 없습니다.</p></div>}{exclusive.length>0&&<div className="guide-note"><Link href="/exclusive-films">이 브랜드의 카메라 전용 필름을 Exclusive Films에서 확인하세요 ↗</Link></div>}</div>}
