import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { exclusiveEntries, exclusiveById } from "@/data/exclusive";
import { cameraById } from "@/data/cameras";
import { filmById } from "@/data/films";
import { brandById } from "@/data/brands";
import { CameraArt, ConfidenceBadge } from "@/components/cards";
import { filmTypeLabel } from "@/lib/format";

type Props={params:Promise<{slug:string}>};
export function generateStaticParams(){return exclusiveEntries.map(x=>({slug:x.id}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const entry=exclusiveById[slug];return {title:entry?`${entry.name} | ${entry.kind==="exclusive"?"Camera Exclusive Film":entry.kind==="unknown"?"Unknown Stock":"Available as Roll"}`:"내장 필름을 찾을 수 없음",description:entry?.description};}
export default async function Page({params}:Props){
  const {slug}=await params;const entry=exclusiveById[slug];if(!entry)notFound();const brand=brandById[entry.brandId];const cameras=entry.cameraIds.map(id=>cameraById[id]).filter(Boolean);const first=cameras[0];const linked=entry.linkedFilmId?filmById[entry.linkedFilmId]:undefined;
  const label=entry.kind==="exclusive"?"CAMERA EXCLUSIVE":entry.kind==="unknown"?"STOCK UNKNOWN":"AVAILABLE AS ROLL";
  return <div className="container page-shell"><div className="detail-breadcrumb"><Link href="/exclusive-films">EXCLUSIVE FILMS</Link> / {entry.name.toUpperCase()}</div><section className="detail-hero"><div><span className="detail-eyebrow">{brand.name.toUpperCase()} · CAMERA STOCK ARCHIVE</span><h1>{entry.name}</h1><p>{entry.description}</p><div className="detail-tags"><span>{label}</span><span>ISO {first.iso||"미확인"}</span><span>{filmTypeLabel[first.filmType]}</span><span>{first.process}</span></div><ConfidenceBadge confidence={first.dataConfidence}/><div className="detail-actions"><Link href={`/camera/${first.id}`} className="primary-button">탑재 카메라 보기 ↗</Link>{linked&&<Link href={`/film/${linked.id}`} className="outline-button">일반 롤 보기 ↗</Link>}</div></div><div className="detail-art-holder"><CameraArt camera={first} large/></div></section><div className="detail-content"><div><section className="content-panel"><h2>별도 롤로 살 수 있나요?</h2><p style={{fontSize:18,color:"#173e67",fontWeight:850}}>{entry.kind==="exclusive"?"이 필름은 일반 롤로는 살 수 없습니다.":entry.kind==="unknown"?"별도 판매 여부를 확인할 수 없습니다.":"같은 필름을 일반 35mm 롤로 구매할 수 있습니다."}</p><p>{entry.kind==="exclusive"?"현재 동일한 일반 135 롤 제품이 확인되지 않습니다. 이 필름은 아래 카메라에서 경험할 수 있습니다.":entry.kind==="unknown"?"정확한 원판 정보는 공개되지 않았습니다. 이름이나 ISO가 비슷한 다른 필름을 동일 제품으로 취급하지 않습니다.":"같은 필름을 일반 롤로 구매할 수 있습니다."}</p></section><section className="content-panel"><h2>탑재 카메라</h2><div className="related-links">{cameras.map(camera=><Link key={camera.id} href={`/camera/${camera.id}`}>{brandById[camera.brandId].name} {camera.name}<span>↗</span></Link>)}</div></section><section className="content-panel"><h2>원판 정보</h2><div className="relation-grid"><div className="relation-card"><small>BRAND</small><b>{brand.name}</b></div><div className="relation-card"><small>ACTUAL STOCK</small><b>{linked?.stockOrigin||"공개되지 않음"}</b></div><div className="relation-card"><small>STANDALONE ROLL</small><b>{entry.kind==="available"?"구매 가능":entry.kind==="exclusive"?"동일 제품 확인되지 않음":"정보 없음"}</b></div><div className="relation-card"><small>EXACT FILM MATCH</small><b>{cameras.every(x=>x.exactFilmMatch)?"확인됨":"확인되지 않음"}</b></div></div></section></div><aside><section className="content-panel"><h2>아카이브 노트</h2><p>{entry.description}</p><p>일회용 카메라의 결과는 내장 필름뿐 아니라 렌즈, 고정 셔터, 조리개와 플래시의 영향을 받습니다.</p><Link className="text-link" href="/guide">용어 가이드 보기 ↗</Link></section>{first.sources?.length?<section className="content-panel"><h2>출처</h2><ul className="source-list">{first.sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.name}</a></li>)}</ul></section>:null}</aside></div></div>;
}
